[project]
name = "art"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitsandbytes>=0.45.2 ; sys_platform == 'linux'",
    "matplotlib>=3.10.1",
    "openai>=1.65.5",
    "seaborn>=0.13.2",
    "torch>=2.5.1",
    "torchao>=0.9.0",
    "torchtune>=0.5.0",
    "vllm>=0.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "black>=25.1.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "skypilot[do,gcp,lambda]>=0.8.0",
]
